spring.application.name=api-gateway

server.port=8085

# USER SERVICE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=${USER_SERVICE_URL:http://user-service:8080}
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

# EVENT SERVICE
spring.cloud.gateway.routes[1].id=event-service
spring.cloud.gateway.routes[1].uri=${EVENT_SERVICE_URL:http://event-service:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/events/**

# BOOKING SERVICE
spring.cloud.gateway.routes[2].id=booking-service
spring.cloud.gateway.routes[2].uri=${BOOKING_SERVICE_URL:http://booking-service:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/bookings/**

# NOTIFICATION SERVICE
spring.cloud.gateway.routes[3].id=notification-service
spring.cloud.gateway.routes[3].uri=${NOTIFICATION_SERVICE_URL:http://notification-service:8083}
spring.cloud.gateway.routes[3].predicates[0]=Path=/notifications/**

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

management.prometheus.metrics.export.enabled=true
