name: Perfect Event CI

on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main
 workflow_dispatch:


jobs:
 build:
  runs-on: ubuntu-latest
  

  steps:

   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Setup Java
     uses: actions/setup-java@v3
     with:
       distribution: temurin
       java-version: 17

   - name: Make Gradle executable
     run: chmod +x ./gradlew

   - name: Build Project
     run: ./gradlew build

   - name: Run tests
     run: ./gradlew test

   - name: Run Checkstyle
     run: ./gradlew check

   - name: Check Gradle
     run: ./gradlew --version

